/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofbd.View;

import javax.swing.JOptionPane;
import projetofbd.DAO.UniversidadeDAO;
import projetofbd.Model.Universidade;

/**
 *
 * @author lucas
 */
public class TelaUniversidade extends javax.swing.JFrame {

    /**
     * Creates new form TelaUniversidade
     */
    public TelaUniversidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUniversidade = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtIdUniversidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeUniversidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUF = new javax.swing.JTextField();
        btnVoltar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAdicionarUniversidade = new javax.swing.JButton();
        btnEditarUniversidade = new javax.swing.JButton();
        btnDeletarUniversidade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universidade");
        setPreferredSize(new java.awt.Dimension(570, 460));
        setResizable(false);

        txtBuscar.setPreferredSize(new java.awt.Dimension(40, 25));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel7.setText("Buscar:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofbd/icones/lupa.png"))); // NOI18N

        tblUniversidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número", "Nome", "Sigla", "UF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUniversidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUniversidadeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUniversidade);

        jLabel2.setText("Numero: ");

        txtIdUniversidade.setEditable(false);

        jLabel3.setText("* Nome:");

        jLabel5.setText("*Sigla:");

        jLabel6.setText("*UF:");

        btnVoltar1.setText("Voltar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("* Campos Obrigatórios");

        btnAdicionarUniversidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofbd/icones/add.png"))); // NOI18N
        btnAdicionarUniversidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarUniversidadeActionPerformed(evt);
            }
        });

        btnEditarUniversidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofbd/icones/edit.png"))); // NOI18N
        btnEditarUniversidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUniversidadeActionPerformed(evt);
            }
        });

        btnDeletarUniversidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofbd/icones/delete.png"))); // NOI18N
        btnDeletarUniversidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarUniversidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdUniversidade, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnAdicionarUniversidade, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(btnEditarUniversidade, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNomeUniversidade)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeletarUniversidade, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdUniversidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNomeUniversidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionarUniversidade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeletarUniversidade, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditarUniversidade)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar1)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tblUniversidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUniversidadeMouseClicked
        // prencher os campos do pesquisador
    }//GEN-LAST:event_tblUniversidadeMouseClicked

    private void btnAdicionarUniversidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarUniversidadeActionPerformed
        // Adcionar pesquisador
        try {
            if (validacao()) {
                JOptionPane.showMessageDialog(null, "Preencha todo os campos obrigátorios.");
            } else {
                Universidade universidade = new Universidade();
                universidade.setNome_Univer(txtNomeUniversidade.getText());
                universidade.setSigla(txtSigla.getText());
                universidade.setUF(txtUF.getText());
                UniversidadeDAO universidadeDAO = new UniversidadeDAO();
                int adicionadao = universidadeDAO.create(universidade);
                if (adicionadao > 0) {
                    JOptionPane.showMessageDialog(null, "Universidade Salva com sucesso.");
                    limparCampos();
                    listarTabelaRevista();
                } else {
                    JOptionPane.showMessageDialog(null, "Não foi possível adicionar a Universidade.");
                    limparCampos();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Universidade já existe");
            limparCampos();
        }

    }//GEN-LAST:event_btnAdicionarUniversidadeActionPerformed

    private void btnEditarUniversidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUniversidadeActionPerformed
        // TODO add your handling code here:
        if (validacao()) {
            JOptionPane.showMessageDialog(null, "Selecione um item, para poder editá-lo.");
        } else {
            Universidade universidade = new Universidade();
            int id = Integer.parseInt(txtIdUniversidade.getText());
            universidade.setCod_Univer((id));
            universidade.setNome_Univer(txtNomeUniversidade.getText());
            universidade.setSigla(txtSigla.getText());
            universidade.setUF(txtUF.getText());
            UniversidadeDAO universidadeDAO = new UniversidadeDAO();
            int editado = universidadeDAO.update(universidade);
            if (editado > 0) {
                JOptionPane.showMessageDialog(null, "Universidade editada com sucesso.");
                limparCampos();
                listarTabelaRevista();
                btnAdicionarUniversidade.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível editar a Universidade.");
            }
        }
    }//GEN-LAST:event_btnEditarUniversidadeActionPerformed

    private void btnDeletarUniversidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarUniversidadeActionPerformed
        // TODO add your handling code here:
        if (txtIdUniversidade.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "Selecione um item, para poder excluí-lo.");
        }else{
            int remove = 0;
            int confirma = JOptionPane.showConfirmDialog(null,"Tem certza que deseja excluir"
                    + " este cliente?", "Atenção!", JOptionPane.YES_OPTION);
            if (confirma == JOptionPane.YES_OPTION){
                Universidade universidade =  new Universidade();
                int id = Integer.parseInt(txtIdUniversidade.getText());
                universidade.setCod_Univer((id));
                universidade.setNome_Univer(txtNomeUniversidade.getText());
                universidade.setSigla(txtSigla.getText());
                universidade.setUF(txtUF.getText());
                
                UniversidadeDAO universidadeDAO = new UniversidadeDAO();
                remove = universidadeDAO.delete(universidade);
                System.out.println(remove);
                if (remove > 0){
                     JOptionPane.showMessageDialog(null, "Pesquisador excluído com sucesso.");
                     limparCampos();
                     listarTabelaRevista();
                     btnAdicionarUniversidade.setEnabled(true);
                     tblUniversidade.setEnabled(true);
                 }else{
                     JOptionPane.showMessageDialog(null, "Não foi possível exluir o Pesquisador.");
                }      
            }
        }
    }//GEN-LAST:event_btnDeletarUniversidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUniversidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUniversidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUniversidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUniversidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUniversidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarUniversidade;
    private javax.swing.JButton btnDeletarUniversidade;
    private javax.swing.JButton btnEditarUniversidade;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUniversidade;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdUniversidade;
    private javax.swing.JTextField txtNomeUniversidade;
    private javax.swing.JTextField txtSigla;
    private javax.swing.JTextField txtUF;
    // End of variables declaration//GEN-END:variables
}
