/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofbd.View;

import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class TelaArtigo extends javax.swing.JFrame {

    /**
     * Creates new form TelaArtigo
     */
    public TelaArtigo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditarRevista = new javax.swing.JButton();
        btnDeletarRevista = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArtigo = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdRevista = new javax.swing.JTextField();
        txtISSN = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter issn = new javax.swing.text.MaskFormatter("####-####");
            txtISSN = new javax.swing.JFormattedTextField(issn);
        }
        catch (Exception e){
        }
        jLabel3 = new javax.swing.JLabel();
        txtEditora = new javax.swing.JTextField();
        txtNomeRevista = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAdicionarRevista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnEditarRevista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofbd/icones/edit.png"))); // NOI18N
        btnEditarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRevistaActionPerformed(evt);
            }
        });

        btnDeletarRevista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofbd/icones/delete.png"))); // NOI18N
        btnDeletarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarRevistaActionPerformed(evt);
            }
        });

        txtBuscar.setPreferredSize(new java.awt.Dimension(40, 25));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("* Campos Obrigatórios");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnVoltar)
                .addComponent(jLabel1))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofbd/icones/lupa.png"))); // NOI18N

        tblArtigo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Titulo", "Página Inicial", "Página FInal", "Ano", "Volume", "Número", "Código da Revista", "Nome do Congresso", "Cidade do Congresso", "Data do Congresso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArtigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblArtigoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblArtigo);

        jLabel5.setText("*Editora:");

        jLabel2.setText("Numero: ");

        jLabel6.setText("*ISSN:");

        txtIdRevista.setEditable(false);

        jLabel3.setText("*Título:");

        jLabel7.setText("Buscar:");

        btnAdicionarRevista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofbd/icones/add.png"))); // NOI18N
        btnAdicionarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarRevistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(62, 62, 62)))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdicionarRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEditarRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(btnDeletarRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNomeRevista))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtISSN, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtISSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarRevista)
                    .addComponent(btnAdicionarRevista)
                    .addComponent(btnDeletarRevista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRevistaActionPerformed
        // TODO add your handling code here:
//        if (validacao()) {
//            JOptionPane.showMessageDialog(null, "Selecione um item, para poder editá-lo.");
//        } else {
//            Revista revista = new Revista();
//            int id = Integer.parseInt(txtIdRevista.getText());
//            revista.setCod_Revista((id));
//            revista.setNome_Revista(txtNomeRevista.getText());
//            revista.setEditora(txtEditora.getText());
//            revista.setISSN(txtISSN.getText());
//            RevistaDAO revistaDAO = new RevistaDAO();
//            int editado = revistaDAO.update(revista);
//            if (editado > 0) {
//                JOptionPane.showMessageDialog(null, "Revista editado com sucesso.");
//                limparCampos();
//                listarTabelaRevista();
//                btnAdicionarRevista.setEnabled(true);
//            } else {
//                JOptionPane.showMessageDialog(null, "Não foi possível editar o Pesquisador.");
//            }
//        }
    }//GEN-LAST:event_btnEditarRevistaActionPerformed

    private void btnDeletarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarRevistaActionPerformed
//        // TODO add your handling code here:
//        if ((txtIdRevista.getText().isEmpty())) {
//            JOptionPane.showMessageDialog(null, "Selecione um item, para poder excluí-lo.");
//        } else {
//            int remove = 0;
//            int confirma = JOptionPane.showConfirmDialog(null, "Tem certza que deseja excluir"
//                + " este cliente?", "Atenção!", JOptionPane.YES_OPTION);
//            if (confirma == JOptionPane.YES_OPTION) {
//                Revista revista = new Revista();
//                int id = Integer.parseInt(txtIdRevista.getText());
//                revista.setCod_Revista((id));
//                revista.setEditora(txtEditora.getText());
//                revista.setISSN(txtISSN.getText());
//
//                RevistaDAO revistaDAO = new RevistaDAO();
//                remove = revistaDAO.delete(revista);
//                System.out.println(remove);
//                if (remove > 0) {
//                    JOptionPane.showMessageDialog(null, "Pesquisador excluído com sucesso.");
//                    limparCampos();
//                    listarTabelaRevista();
//                    btnAdicionarRevista.setEnabled(true);
//                    tblRevista.setEnabled(true);
//                } else {
//                    JOptionPane.showMessageDialog(null, "Não foi possível exluir o Pesquisador.");
//                }
//            }
//        }
    }//GEN-LAST:event_btnDeletarRevistaActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        try {
//            listarTabelaRevista();
            tblArtigo.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na transação");
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

        voltar();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void voltar() {
        TelaPrincipal telaprincipal = new TelaPrincipal();
        telaprincipal.setVisible(true);
        this.dispose();
    }

    private void tblArtigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArtigoMouseClicked
        // prencher os campos do pesquisador
//        setarCampos();
    }//GEN-LAST:event_tblArtigoMouseClicked

    public void setarCampos() {
//        int setar = tblArtigo.getSelectedRow();
//        txt.setText(tblPesquisador.getModel().getValueAt(setar, 0).toString());
//        txtNomePesquisador.setText(tblPesquisador.getModel().getValueAt(setar, 1).toString());
//        txtUniversidade.setText(tblPesquisador.getModel().getValueAt(setar, 2).toString());
//        // A linha abaixo desabilitar o botão adicionar

    }
    private void btnAdicionarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarRevistaActionPerformed
        // Adcionar pesquisador
//        try {
//            if (validacao()) {
//                JOptionPane.showMessageDialog(null, "Preencha todo os campos obrigátorios.");
//            } else {
//                Revista revista = new Revista();
//                revista.setNome_Revista(txtNomeRevista.getText());
//                revista.setEditora(txtEditora.getText());
//                revista.setISSN(txtISSN.getText());
//                RevistaDAO revistaDAO = new RevistaDAO();
//                int adicionadao = revistaDAO.create(revista);
//                if (adicionadao > 0) {
//                    JOptionPane.showMessageDialog(null, "Revista Salva com sucesso.");
//                    limparCampos();
////                    listarTabelaRevista();
//                } else {
//                    JOptionPane.showMessageDialog(null, "Não foi possível adicionar o Pesquisador.");
////                    limparCampos();
//                }
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Revista já existe");
////            limparCampos();
//        }
    }//GEN-LAST:event_btnAdicionarRevistaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Voltar página principal
        this.voltar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaArtigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarRevista;
    private javax.swing.JButton btnDeletarRevista;
    private javax.swing.JButton btnEditarRevista;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArtigo;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtISSN;
    private javax.swing.JTextField txtIdRevista;
    private javax.swing.JTextField txtNomeRevista;
    // End of variables declaration//GEN-END:variables
}
